export const mockData = [
    {
        id: 1,
        title: "&#39;React for Beginners&#39;",
        author: "&#39;John Doe&#39;",
        price: 19.99,
        stock: 5,
    },
    {
        id: 2,
        title: "&#39;Advanced JavaScript&#39;",
        author: "&#39;Jane Smith&#39;",
        price: 29.99,
        stock: 3,
    },
    {
        id: 3,
        title: "&#39;Understanding TypeScript&#39;",
        author: "&#39;Michael Brown&#39;",
        price: 24.99,
        stock: 7,
    },
    {
        id: 4,
        title: "&#39;Mastering Node.js&#39;",
        author: "&#39;Sarah Williams&#39;",
        price: 34.99,
        stock: 2,
    },
    {
        id: 5,
        title: "&#39;CSS for Dummies&#39;",
        author: "&#39;Emily Davis&#39;",
        price: 15.99,
        stock: 8,
    },
    {
        id: 6,
        title: "&#39;Web Performance Optimization&#39;",
        author: "&#39;David Johnson&#39;",
        price: 39.99,
        stock: 4,
    },
    {
        id: 7,
        title: "&#39;React Native in Action&#39;",
        author: "&#39;Richard Lee&#39;",
        price: 49.99,
        stock: 6,
    },
    {
        id: 8,
        title: "&#39;JavaScript: The Good Parts&#39;",
        author: "&#39;Douglas Crockford&#39;",
        price: 14.99,
        stock: 10,
    },
    {
        id: 9,
        title: "&#39;Building Scalable Web Applications&#39;",
        author: "&#39;Anna Taylor&#39;",
        price: 29.99,
        stock: 3,
    },
    {
        id: 10,
        title: "&#39;Python for Data Science&#39;",
        author: "&#39;Chris Martin&#39;",
        price: 39.99,
        stock: 5,
    },
];